/*

 HUTSMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Sebagala Kimuli\Desktop\Graphics\BackgroundTiles\Idk.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define HutsMapWidth 20
#define HutsMapHeight 18
#define HutsMapBank 0

extern unsigned char HutsMap[];

/* End of HUTSMAP.H */
