/*

 KRYS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 9

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define KrysBank 0

/* Super Gameboy palette 0 */
#define KrysSGBPal0c0 6076
#define KrysSGBPal0c1 8935
#define KrysSGBPal0c2 6596
#define KrysSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define KrysSGBPal1c0 6076
#define KrysSGBPal1c1 8935
#define KrysSGBPal1c2 6596
#define KrysSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define KrysSGBPal2c0 6076
#define KrysSGBPal2c1 8935
#define KrysSGBPal2c2 6596
#define KrysSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define KrysSGBPal3c0 6076
#define KrysSGBPal3c1 8935
#define KrysSGBPal3c2 6596
#define KrysSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define KrysCGBPal0c0 32767
#define KrysCGBPal0c1 18044
#define KrysCGBPal0c2 31810
#define KrysCGBPal0c3 7202

/* Gameboy Color palette 1 */
#define KrysCGBPal1c0 32767
#define KrysCGBPal1c1 21140
#define KrysCGBPal1c2 10570
#define KrysCGBPal1c3 0

/* Gameboy Color palette 2 */
#define KrysCGBPal2c0 6076
#define KrysCGBPal2c1 8935
#define KrysCGBPal2c2 6596
#define KrysCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define KrysCGBPal3c0 6076
#define KrysCGBPal3c1 8935
#define KrysCGBPal3c2 6596
#define KrysCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define KrysCGBPal4c0 6076
#define KrysCGBPal4c1 8935
#define KrysCGBPal4c2 6596
#define KrysCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define KrysCGBPal5c0 6076
#define KrysCGBPal5c1 8935
#define KrysCGBPal5c2 6596
#define KrysCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define KrysCGBPal6c0 6076
#define KrysCGBPal6c1 8935
#define KrysCGBPal6c2 6596
#define KrysCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define KrysCGBPal7c0 6076
#define KrysCGBPal7c1 8935
#define KrysCGBPal7c2 6596
#define KrysCGBPal7c3 5344
/* CGBpalette entries. */
